server:
  port : 8081
spring:
  main:
    banner-mode: "off"
  konnecticator:
    offsets-store-name: "offsets-store"
    offsets-cluster-topic: ${KONNECTICATOR_OFFSETS_TOPIC}
    configs-store-name: "configs-store"
    configs-cluster-topic: ${KONNECTICATOR_CONFIGS_TOPIC}
    status-store-name: "status-store"
    status-cluster-topic: ${KONNECTICATOR_STATUS_TOPIC}
    connect-cluster-rest-endpoint: ${KONNECTICATOR_CLUSTER_ENDPOINT}
  kafka:
    client-id: konnecticator
    bootstrap-servers: ${BOOTSTRAP_SERVERS}
    # properties:
    #   ssl.endpoint.identification.algorithm: https
    #   sasl.mechanism: PLAIN
    #   sasl.jaas.config: ${SASL_JAAS_CONFIG}
    #   security.protocol: SASL_SSL
    consumer:
      group-id: konnecticator-server-consumer
    streams:
      application-id: konnecticator-server-local
      properties:
        commit:
          interval:
            ms: 0
        default:
          key:
            serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          value:
            serde: org.apache.kafka.common.serialization.Serdes$StringSerde
logging:
  level:
    root: INFO
